[package]
name = "magic-link"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
email_address = "0.2.4"
lettre = "0.10.4"
redis = "0.23.0"
rocket = "0.5.0-rc.3"
rocket_db_pools = { version = "0.1.0-rc.2", features = [ "deadpool_redis" ] }
sha2 = "0.10.7"
toml = "0.4.2"
